import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import FAB from "@/components/FABWhatsapp";
import { LanguageProvider } from "@/context/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Villa Tolping",
  description: "Generated by create next appA cozy and tranquil villa featuring complete facilities and a serene natural atmosphere — the perfect choice for a relaxing and memorable getaway, Villa nyaman dan tenang dengan fasilitas lengkap serta suasana alami yang menenangkan — pilihan tepat untuk liburan santai dan berkesan, villa di bogor, villa di puncak, villa keluarga, villa murah, villa untuk acara, sewa villa, rental villa, penginapan di bogor, penginapan di puncak, villa di megamendung, villa modern",

  keywords: [
    "villa tolping",
    "villa tolping puncak",
    "villa tolping bogor",
    "villa tolping megamendung",
    "villa di bogor",
    "villa di puncak",
    "villa keluarga di bogor puncak",
    "villa murah di bogor puncak",
    "villa untuk acara di bogor puncak",
    "sewa villa di bogor puncak",
    "rental villa di bogor puncak",
    "penginapan di bogor puncak",
    "penginapan di bogor puncak",
    "villa di megamendung puncak",
    "villa modern di bogor puncak"
  ],

  robots: {
    index: true,
    follow: true
  },

  alternates: {
    canonical: "https://villatolping.web.id/",
  },

  openGrapg: {
    title: "Villa Tolping | Villa Nyaman di Puncak Bogor",
    description: "Villa nyaman di Puncak Bogor dengan fasilitas lengkap dan suasana alami.",
    url: "https://villatolping.web.id/",
    siteName: "Villa Tolping",
    locale: "id_ID",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Villa Tolping",
    description: "Villa nyaman dan tenang di Puncak Bogor dengan fasilitas lengkap dan suasana alami yang berkesan.",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          {children}
        </LanguageProvider>
        <FAB/>
      </body>
    </html>
  );
}
