import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import FAB from "@/components/FABWhatsapp";
import { Fa0 } from "react-icons/fa6";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Villa Tolping",
  description: "Generated by create next appA cozy and tranquil villa featuring complete facilities and a serene natural atmosphere — the perfect choice for a relaxing and memorable getaway, Villa nyaman dan tenang dengan fasilitas lengkap serta suasana alami yang menenangkan — pilihan tepat untuk liburan santai dan berkesan, villa di bogor, villa di puncak, villa keluarga, villa murah, villa untuk acara, sewa villa, rental villa, penginapan di bogor, penginapan di puncak, villa di megamendung, villa modern"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <FAB/>
      </body>
    </html>
  );
}
